### ISSUE TITLE
Register command return codes

### ISSUE THREAD

**Issue by mbovo** [mbovo/yacasc#5]
implement something in order to save returned values of a command in a variable

```yaml
- name: Download
  src: bla
  dest: bla
  register: myvar
```
